parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\[\e[1;31m\]$(parse_git_branch)\[\e[0m\]$ "
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad