#!/bin/bash

echo "Converting ipython notebooks to .rst"

TUTORIAL_IPYNB="../tutorial/"
TUTORIAL_RST="../docs/_tutorial/"

ipython nbconvert ${TUTORIAL_IPYNB}/notes.ipynb --to rst --output-dir=${TUTORIAL_RST}